### ISSUE TITLE
Client side socket timeout while waiting for RSA key generation

### ISSUE THREAD

**Issue by JustScott** [JustScott/SuperSockets#1]
<h1 align='center'>Client Side Socket Timeout While Waiting To Receive RSA Key</h1>

<h2>Error:</h2>

```python
Traceback (most recent call last):
  File "client.py", line 3, in <module>
    client = connect(ip='0.0.0.0', port=1234, connection_type="client")
  File "/home/user/venv/lib/python3.8/site-packages/supersockets/supersockets.py", line 106, in __init__
    self.create_secure_connection(RSA)
  File "/home/user/venv/lib/python3.8/site-packages/supersockets/supersockets.py", line 146, in create_secure_connection
    public_key = self.recv() ##
  File "/home/user/venv/lib/python3.8/site-packages/supersockets/supersockets.py", line 226, in recv
    received = self.con.recv(1024)
socket.timeout: timed out
```
<h2 align='center'>Temproray Fix: </h2>

<h4>For slower hardware, the default 3 second 'socket_timeout' time period may not be enough.
Until a fix is provided add a longer 'socket_timeout' when configuring your client connection</h3>
<h3>example:</h3>

```python
client = connect(ip='0.0.0.0', port=1234, connection_type='client', socket_timeout=20)
```

**Comment by JustScott** [comment]
Issue Fixed!
